#pragma once
#define INIT_SCREEN_TITLE "Atmospheric"
#define INIT_SCREEN_WIDTH 1280
#define INIT_SCREEN_HEIGHT 960
#define SINGLE_THREAD 0
#define RUNTIME_LOG_ON 0
#define SHOW_PROCESS_COST 0
#define SHOW_RENDER_AND_DRAW_COST 1
#define SHOW_SYNC_COST 0
