name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fase: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        build-type: [debug, release]
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Bootstrap vcpkg
        run: |
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake

      - name: Install EMSDK
        shell: base
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Expose EMSDK
        run:
          source ./emsdk/emsdk_env.sh


      - name: CMake configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=MinSizeRel

      - name: CMake build
        run: |
          cmake --build build

      - uses: actions/upload-artifact@v2
        with:
          path: build/*.tar.gz
          name: artifact_${{ matrix.os }}_${{ matrix.configs }}.tar.gz